---
title: "About"
---

Ce site web est un compagnon du hackathon non compétitif 
proposé par l'Insee et le service statistique du ministère
de l'agriculture sur le thème _"Du champ à l'assiette"_


## Ressources utiles

Liste des sujets: 

- [Sujet 1 : 150 ans d'agriculture en France](https://github.com/InseeFrLab/funathon2023_sujet1)
Une initiation à la dataviz avec observable sur séries longues
- [Sujet 2 : Explorer la géographie des cultures agricoles françaises](https://github.com/InseeFrLab/funathon2023_sujet2)
Une exploration de la géographie des cultures agricoles
- [Sujet 3 : Explorer les habitudes alimentaires de nos compatriotes](https://github.com/InseeFrLab/funathon2023_sujet3)
Une initiation à l'analyse exploratoire de données et au clustering
- [Sujet 4 : Produire une application qui scanne le code barre d'un produit et donne sa composition nutritionnelle](https://github.com/InseeFrLab/funathon2023_sujet4)
Un parcours guidé pour créer une application de lecture de code barre avec Python à la manière de Yuka
- [Sujet 5 : Analyse textuelle des commentaires clients de restaurants](https://github.com/InseeFrLab/funathon2023_sujet5)
Analyse de sentiments dans des commentaires clients à partir de données scrappées
- [Sujet 6 : A la recherche de l'alimentation perdue](https://github.com/InseeFrLab/funathon2023_sujet6)
Traitement du langage, rechercher toutes les références à des aliments dans l’oeuvre de Proust


Replay de la présentation du 16 juin (présentation du principe de l'événement, présentation du SSP Cloud et de l'usage de `Git`):
__INCOMING__

Dépôt `Github` centralisant le contenu de ce site web: https://github.com/InseeFrLab/funathon2023